main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Research
    pageRef: /research
    weight: 20
  - name: Teaching
    pageRef: /teaching
    weight: 30
  - name: CV
    pageRef: /cv
    weight: 40
